METRA_BASE = "https://gtfsapi.metrarail.com/gtfs"
METRA_API_KEY = ""
METRA_SECRET_KEY = ""

DASH_FMT  = r'%Y-%m-%d'
SLASH_FMT = r'%m/%d/%Y'

SCHEDULES_BASE = "https://metrarail.com/maps-schedules"

ROUTE_NAMES = {
    "Burlington Northern":"BNSF",
    "Heritage Corridor":"HC",
    "Milwaukee District North":"MD-N",
    "Milwaukee District West":"MD-W",
    "Metra Electric":"ME",
    "North Central Services":"NCS",
    "Rock Island":"RI",
    "SouthWest Service":"SWS",
    "Union Pacific North":"UP-N",
    "Union Pacific Northwest":"UP-NW",
    "Union Pacific West":"UP-W"}

ROUTES_SHORTHAND = {
    "bnsf":"BNSF",
    "hc":"HC",
    "mdn":"MD-N",
    "md-n":"MD-N",
    "mdw":"MD-W",
    "md-w":"MD-W",
    "me":"ME",
    "ncs":"NCS",
    "ri":"RI",
    "sws":"SWS",
    "upn":"UP-N",
    "up-n":"UP-N",
    "upnw":"UP-NW",
    "up-nw":"UP-NW",
    "upw":"UP-W",
    "up-w":"UP-W"}

ZONES = {
    "GENEVA": "H",
    "WCHICAGO": "F",
    "WINFIELD": "F",
    "WHEATON": "E",
    "COLLEGEAVE": "E",
    "GLENELLYN": "E",
    "LOMBARD": "D",
    "VILLAPARK": "D",
    "ELMHURST": "D",
    "BERKELEY": "C",
    "BELLWOOD": "C",
    "MELROSEPK": "C",
    "MAYWOOD": "C",
    "RIVRFOREST": "B",
    "OAKPARK": "B",
    "KEDZIE": "A",
    "AURORA": "H",
    "ROUTE59": "G",
    "NAPERVILLE": "F",
    "LISLE": "E",
    "BELMONT": "E",
    "MAINST-DG": "E",
    "FAIRVIEWDG": "E",
    "WESTMONT": "D",
    "CLARNDNHIL": "D",
    "WHINSDALE": "D",
    "HINSDALE": "D",
    "HIGHLANDS": "D",
    "WESTSPRING": "D",
    "STONEAVE": "C",
    "LAGRANGE": "C",
    "CONGRESSPK": "C",
    "BROOKFIELD": "C",
    "HOLLYWOOD": "C",
    "RIVERSIDE": "C",
    "HARLEM": "B",
    "BERWYN": "B",
    "LAVERGNE": "B",
    "CICERO": "B",
    "BNWESTERN": "A",
    "HALSTED": "A",
    "JOLIET": "H",
    "LOCKPORT": "G",
    "LEMONT": "E",
    "WILLOWSPRN": "D",
    "SUMMIT": "C",
    "179TH-SWS": "F",
    "153RD-SWS": "E",
    "143RD-SWS": "E",
    "PALOSPARK": "E",
    "WORTH": "D",
    "CHICRIDGE": "D",
    "OAKLAWN": "D",
    "ASHBURN": "C",
    "WRIGHTWOOD": "C",
    "CLYBOURN": "A",
    "RAVENSWOOD": "B",
    "ROGERPK": "B",
    "MAINST": "C",
    "EVANSTON": "C",
    "CENTRALST": "C",
    "WILMETTE": "C",
    "KENILWORTH": "D",
    "WINNETKA": "D",
    "HUBARDWOOD": "D",
    "GLENCOE": "D",
    "BRAESIDE": "E",
    "RAVINIA": "E",
    "HIGHLANDPK": "E",
    "HIGHWOOD": "E",
    "FTSHERIDAN": "F",
    "LKFOREST": "F",
    "LAKEBLUFF": "G",
    "GRTLAKES": "G",
    "NCHICAGO": "G",
    "WAUKEGAN": "H",
    "ZION": "I",
    "WINTHROP": "I",
    "FOXLAKE": "J",
    "INGLESIDE": "J",
    "LONGLAKE": "J",
    "ROUNDLAKE": "I",
    "GRAYSLAKE": "I",
    "LIBERTYVIL": "H",
    "LAKEFRST": "F",
    "DEERFIELD": "E",
    "LAKECOOKRD": "E",
    "NBROOK": "E",
    "NGLENVIEW": "D",
    "GLENVIEW": "D",
    "GOLF": "D",
    "MORTONGRV": "C",
    "EDGEBROOK": "C",
    "FORESTGLEN": "C",
    "MAYFAIR": "B",
    "GRAYLAND": "B",
    "HEALY": "B",
    "WESTERNAVE": "A",
    "RAVINIAPK": "E",
    "INDIANHILL": "D",
    "KENOSHA": "J",
    "HARVARD": "J",
    "WOODSTOCK": "J",
    "CRYSTAL": "I",
    "MCHENRY": "J",
    "CARY": "H",
    "FOXRG": "H",
    "BARRINGTON": "G",
    "PALATINE": "F",
    "ARLINGTNPK": "E",
    "ARLINGTNHT": "E",
    "MTPROSPECT": "D",
    "CUMBERLAND": "D",
    "DESPLAINES": "D",
    "DEEROAD": "C",
    "PARKRIDGE": "C",
    "IRVINGPK": "B",
    "BIGTIMBER": "H",
    "ELGIN": "H",
    "NATIONALS": "H",
    "HANOVERP": "F",
    "SCHAUM": "F",
    "ROSELLE": "E",
    "MEDINAH": "E",
    "ITASCA": "E",
    "WOODDALE": "D",
    "BENSENVIL": "D",
    "MANNHEIM": "C",
    "FRANKLIN": "C",
    "MONTCLARE": "B",
    "MARS": "B",
    "GALEWOOD": "B",
    "HANSONPK": "B",
    "GRAND-CIC": "B",
    "OHARE": "D",
    "PROSPECTHG": "E",
    "WHEELING": "F",
    "BUFFGROVE": "F",
    "PRAIRIEVW": "G",
    "VERNON": "G",
    "MUNDELEIN": "H",
    "PRAIRCROSS": "H",
    "ROUNDLKBCH": "J",
    "LAKEVILLA": "J",
    "ANTIOCH": "J",
    "NEWLENOX": "G",
    "MOKENA": "F",
    "HICKORYCRK": "F",
    "TINLEY80TH": "E",
    "TINLEYPARK": "E",
    "OAKFOREST": "E",
    "MIDLOTHIAN": "D",
    "ROBBINS": "D",
    "KENSINGTN": "C",
    "59TH-UP": "B",
    "UNIVERSITY": "G",
    "RICHTON": "F",
    "MATTESON": "F",
    "211TH-UP": "F",
    "OLYMPIA": "F",
    "FLOSSMOOR": "E",
    "HOMEWOOD": "E",
    "CALUMET": "E",
    "EDISONPK": "C",
    "NORWOODP": "C",
    "GLADSTONEP": "B",
    "JEFFERSONP": "B",
    "BARTLETT": "F",
    "47TH-UP": "B",
    "51ST-53RD": "B",
    "55-56-57TH": "B",
    "63RD-UP": "B",
    "PRAIRIEXNG": "H",
    "RIVERGROVE": "C",
    "ELMWOODPK": "C",
    "RIVERDALE": "D",
    "IVANHOE": "D",
    "147TH-UP": "D",
    "HARVEY": "D",
    "HAZELCREST": "E",
    "MILLENNIUM": "A",
    "VANBUREN": "A",
    "MUSEUM": "A",
    "18TH-UP": "A",
    "MCCORMICK": "A",
    "27TH-UP": "A",
    "75TH-UP": "B",
    "79TH-UP": "B",
    "83RD-UP": "B",
    "87TH-UP": "B",
    "91ST-UP": "C",
    "95TH-UP": "C",
    "103RD-UP": "C",
    "107TH-UP": "C",
    "111TH-UP": "C",
    "STONYISLND": "B",
    "BRYNMAWR": "B",
    "SOUTHSHORE": "B",
    "WINDSORPK": "B",
    "79TH-SC": "B",
    "83RD-SC": "B",
    "87TH-SC": "B",
    "93RD-SC": "B",
    "LSS": "A",
    "GRESHAM": "B",
    "VERMONT": "D",
    "LONGWOOD": "C",
    "WASHHGTS": "C",
    "BRAINERD": "C",
    "91ST-BEV": "C",
    "PRAIRIEST": "D",
    "123RD-BEV": "C",
    "119TH-BEV": "C",
    "115TH-BEV": "C",
    "111TH-BEV": "C",
    "107TH-BEV": "C",
    "103RD-BEV": "C",
    "99TH-BEV": "C",
    "95TH-BEV": "C",
    "BLUEISLAND": "D",
    "BURROAK": "D",
    "ASHLAND": "C",
    "RACINE": "C",
    "WPULLMAN": "C",
    "STEWARTRID": "C",
    "STATEST": "C",
    "SCHILLERPK": "C",
    "PALOSHTS": "D",
    "PINGREE": "I",
    "CUS": "A",
    "OTC": "A",
    "LARAWAY": "H",
    "MANHATTAN": "I",
    "NCSGRAYSLK": "I",
    "ROSEMONT": "D",
    "FRANKLINPK": "C",
    "LAFOX": "I",
    "ELBURN": "I",
    "35TH": "A",
    "ROMEOVILLE": "F",
    }


